concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number
    || github.sha }}
defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}
env:
  CONTINUOUS_INTEGRATION: true
  MAVEN: ./mvnw
  MAVEN_FAST_INSTALL: -B --strict-checksums -V --quiet -T 1C -DskipTests -Dair.check.skip-all
  MAVEN_INSTALL_OPTS: -Xmx2G -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000
  MAVEN_OPTS: -Xmx512M -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000
  MAVEN_TEST: -B --strict-checksums -Dair.check.skip-all --fail-at-end
  RETRY: .github/bin/retry
jobs:
  docs-checks:
    if: ${{ needs.path-filters.outputs.docs == 'true' && needs.path-filters.outputs.other
      == 'false' }}
    needs: path-filters
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      timeout-minutes: 10
      uses: ./.github/actions/setup
    - continue-on-error: true
      name: Maven Checks
      run: 'export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"

        $RETRY $MAVEN install -B --strict-checksums -V -T 1C -DskipTests -P ci -am
        -pl '':trino-docs''

        '
    - continue-on-error: true
      if: steps.cache.outputs.cache-hit != 'true'
      name: Clean local Maven repo
      run: rm -rf ~/.m2/repository
    timeout-minutes: 45
  path-filters:
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      other: ${{ steps.filter.outputs.other }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
      with:
        filters: 'docs: ''docs/**''

          other: ''!docs/**''

          '
  test-docs:
    if: ${{ needs.path-filters.outputs.docs == 'true' && needs.path-filters.outputs.other
      == 'false' && !contains(github.event.pull_request.labels.*.name, 'release-notes')
      }}
    needs: path-filters
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      timeout-minutes: 10
      uses: ./.github/actions/setup
    - continue-on-error: true
      name: Maven Install
      run: 'export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"

        $RETRY $MAVEN install ${MAVEN_FAST_INSTALL} -am -pl $(echo ''${{ matrix.modules
        }}'' | cut -d'' '' -f1)

        '
    - continue-on-error: true
      id: tests
      name: Maven Tests
      run: $MAVEN test ${MAVEN_TEST} -pl ${{ matrix.modules }}
    - continue-on-error: true
      if: always()
      name: Sanitize artifact name
      run: '# Generate a valid artifact name and make it available to next steps as

        # an environment variable ARTIFACT_NAME

        # ", :, <, >, |, *, ?, \, / are not allowed in artifact names but we only
        use : so we remove it

        name=$(echo -n "${{ matrix.modules }}" | sed -e ''s/[:]//g'')

        echo "ARTIFACT_NAME=$name" >> $GITHUB_ENV

        '
    - continue-on-error: true
      if: always()
      name: Upload test results
      uses: ./.github/actions/process-test-results
      with:
        artifact-name: ${{ env.ARTIFACT_NAME }}
        has-failed-tests: ${{ steps.tests.outcome == 'failure' }}
    - continue-on-error: true
      if: steps.cache.outputs.cache-hit != 'true'
      name: Clean local Maven repo
      run: rm -rf ~/.m2/repository
    strategy:
      fail-fast: false
      matrix:
        modules:
        - :trino-main
        - :trino-plugin-toolkit
        - :trino-resource-group-managers
        - :trino-tests
    timeout-minutes: 60
name: docs
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
