defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}
jobs:
  set-milestone:
    if: github.repository_owner == 'trinodb'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      timeout-minutes: 10
      uses: ./.github/actions/setup
    - continue-on-error: true
      name: Get milestone from pom.xml
      run: '.github/bin/retry ./mvnw -v

        MILESTONE_NUMBER="$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout
        | cut -d- -f1)"

        echo "Setting PR milestone to ${MILESTONE_NUMBER}"

        echo "MILESTONE_NUMBER=${MILESTONE_NUMBER}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Set milestone to PR
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: "// Get pull request number from commit sha\n// 'listPullRequestsAssociatedWithCommit()'\
          \ lists the merged pull request\n// https://docs.github.com/en/rest/reference/repos#list-pull-requests-associated-with-a-commit\n\
          // and https://octokit.github.io/rest.js/v19#repos-list-pull-requests-associated-with-commit\n\
          const pr_response = await github.rest.repos.listPullRequestsAssociatedWithCommit({\n\
          \    owner: context.repo.owner,\n    repo: context.repo.repo,\n    commit_sha:\
          \ context.sha\n})\nif (pr_response.data.length === 0) {\n    console.log('Pull\
          \ request not found for commit', context.sha)\n    return\n}\nif (pr_response.data.length\
          \ > 1) {\n    console.log(pr_response.data)\n    throw 'Expected 1 pull\
          \ request but found: ' + pr_response.data.length\n}\nconst pr_number = pr_response.data[0].number\n\
          console.log('Found pull request', pr_number, 'for commit', context.sha)\n\
          \n// Get milestone\nconst {\n    MILESTONE_NUMBER\n} = process.env\nconsole.log('Milestone\
          \ number to set', MILESTONE_NUMBER)\n\n// Find milestone with matching title\n\
          // See https://octokit.github.io/rest.js/v19#pagination\nconst milestones\
          \ = await github.paginate(github.rest.issues.listMilestones, {\n    owner:\
          \ context.repo.owner,\n    repo: context.repo.repo,\n    state: 'all'\n\
          })\nlet milestone = milestones.find(milestone => milestone.title === MILESTONE_NUMBER)\n\
          console.log('Found milestone with title', MILESTONE_NUMBER, milestone)\n\
          \n// Create new milestone if it doesn't exist\nif (!milestone) {\n    const\
          \ create_response = await github.rest.issues.createMilestone({\n       \
          \ owner: context.repo.owner,\n        repo: context.repo.repo,\n       \
          \ title: MILESTONE_NUMBER\n    })\n    milestone = create_response.data\n\
          \    console.log('Created new milestone with title', MILESTONE_NUMBER, milestone)\n\
          }\n\n// Set milestone to PR\nawait github.rest.issues.update({\n    owner:\
          \ context.repo.owner,\n    repo: context.repo.repo,\n    milestone: milestone.number,\n\
          \    issue_number: pr_number\n})\nconsole.log('Added PR', pr_number, 'to\
          \ milestone', MILESTONE_NUMBER)\n"
name: milestone
on:
  repository_dispatch:
    types: trigger-ga___milestone.yml
