jobs:
  test-with-secrets:
    if: ${{ github.event.issue.pull_request }} && github.repository_owner == 'trinodb'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: generate_token
      name: Generate token
      uses: trinodb/github-actions/github-app-token@2c3f458fcad343199d0e92badaaa6e9dd7993b2e
      with:
        app_id: ${{ secrets.SERVICE_ACCOUNT_APP_ID }}
        private_key: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
    - continue-on-error: true
      env:
        TOKEN: ${{ steps.generate_token.outputs.token }}
      name: Slash Command Dispatch
      uses: trinodb/github-actions/slash-command-dispatch@2c3f458fcad343199d0e92badaaa6e9dd7993b2e
      with:
        commands: test-with-secrets
        issue-type: pull-request
        permission: write
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        token: ${{ env.TOKEN }}
name: Ok To Test
on:
  repository_dispatch:
    types: trigger-ga___ok-to-test.yml
