jobs:
  stale:
    if: github.repository == 'trinodb/trino'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9.0.0
      with:
        close-pr-message: Closing this pull request, as it has been stale for six
          weeks. Feel free to re-open at any time.
        days-before-issue-close: -1
        days-before-issue-stale: -1
        days-before-pr-close: 21
        days-before-pr-stale: 21
        exempt-draft-pr: true
        exempt-pr-labels: stale-ignore
        operations-per-run: 200
        stale-pr-label: stale
        stale-pr-message: 'This pull request has gone a while without any activity.
          Tagging the Trino developer relations team: @bitsondatadev @colebow @mosabua'
        start-date: '2023-01-01T00:00:00Z'
name: Stale PR tracking
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  pull-requests: write
